"""
Writer node — synthesizes research dossiers into an executive brief (Opus).
"""

import json
import logging
from typing import Any

from langchain_anthropic import ChatAnthropic
from langchain_core.messages import HumanMessage, SystemMessage
from anthropic import InternalServerError, RateLimitError
from tenacity import retry, retry_if_exception_type, stop_after_attempt, wait_exponential

from competitive_intel.callbacks import UsageTracker
from competitive_intel.config import ANTHROPIC_API_KEY, DRAFTS_DIR, MODEL_QUALITY, today_str
from competitive_intel.state import PipelineState

log = logging.getLogger(__name__)

# ── Module-level LLM singleton ────────────────────────────────────────────────
_LLM = ChatAnthropic(
    model=MODEL_QUALITY,
    api_key=ANTHROPIC_API_KEY,
    max_tokens=4096,
)

SYSTEM_PROMPT = """\
You are an expert business intelligence writer. You produce clear, concise
competitive intelligence briefs for executive audiences.

Your brief should follow this structure:

# Competitive Intelligence Brief — {date}

## Executive Summary
(3-5 sentences covering the most important findings across all competitors)

## Competitor Highlights
(One subsection per competitor with the most notable developments)

## Key Trends
(Cross-cutting themes you observe across the competitive landscape)

## Recommended Actions
(2-4 specific, actionable recommendations for leadership)

---
*Generated by AI Competitive Intelligence Pipeline*

Write in clear, professional prose. Use markdown formatting.
Be specific — cite the competitor name when making claims.
Keep the total brief under 1500 words. Use the research data provided; cite sources where relevant.
"""


@retry(
    stop=stop_after_attempt(5),
    wait=wait_exponential(multiplier=2, min=5, max=60),
    retry=retry_if_exception_type((InternalServerError, RateLimitError, Exception)),
    reraise=True,
)
def _invoke_llm(messages: list) -> Any:
    return _LLM.invoke(messages, config={"callbacks": [UsageTracker()]})


def writer_node(state: PipelineState) -> dict[str, Any]:
    """Produce or revise the brief from research (and optional critic feedback)."""
    research = state.get("research") or []
    feedback = state.get("feedback")
    revision_count = state.get("revision_count") or 0

    if not research:
        return {"brief": ""}

    date = today_str()
    is_revision = feedback and revision_count > 0 and feedback.get("revision_instructions")
    log.info("Writing brief (%s)", "revision" if is_revision else "initial draft")

    research_block = "\n\n---\n\n".join(json.dumps(r, indent=2) for r in research)
    user_content = (
        f"Here are the research dossiers for today ({date}):\n\n"
        f"{research_block}\n\n"
        "Please write the competitive intelligence brief."
    )
    if is_revision:
        user_content += (
            "\n\n--- REVISION REQUEST ---\n"
            "A critic has reviewed the previous draft and provided this feedback:\n\n"
            f"{feedback['revision_instructions']}\n\n"
            "Please produce an improved version addressing this feedback."
        )

    messages = [
        SystemMessage(content=SYSTEM_PROMPT.replace("{date}", date)),
        HumanMessage(content=user_content),
    ]
    response = _invoke_llm(messages)
    brief = response.content if hasattr(response, "content") else str(response)
    if isinstance(brief, list):
        brief = "".join(getattr(b, "text", str(b)) for b in brief)
    elif not isinstance(brief, str):
        brief = str(brief)

    if is_revision:
        revision_count += 1

    # Save draft to disk
    try:
        suffix = f"_rev{revision_count}" if revision_count > 0 else ""
        path = DRAFTS_DIR / f"{date}_brief{suffix}.md"
        path.write_text(brief, encoding="utf-8")
        log.info("Wrote draft: %s (%d chars)", path.name, len(brief))
    except Exception as exc:
        log.warning("Failed to write draft: %s", exc)

    return {"brief": brief, "revision_count": revision_count}
